# Generated by Django 5.2.7 on 2025-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
