# Generated by Django 5.2.7 on 2025-12-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='ride_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
