# Generated by Django 5.2.7 on 2025-12-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('rides', '0002_alter_payments_ride_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='rides',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rides',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
