# Generated by Django 5.2.7 on 2025-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_rides_updated_at_alter_rides_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('in process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in process', max_length=20),
        ),
    ]
