# Generated by Django 5.2.7 on 2025-12-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_rides_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='seat_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
