# Generated by Django 5.2.7 on 2025-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ridebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
