# Generated by Django 5.2.7 on 2025-12-27 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_ridebooking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridebooking',
            name='booked_at',
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.rides'),
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
